### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by maticstric** [bobrk/jules-verne_facing-the-flag_f-tennyson-neely#1]
- [x] `se clean` makes changes
- [x] "Drags were used and diverse sent down" was incorrectly changed to "diverse" in an editorial commit. Same for "There are many expert diverse among our men". You're going to need to edit the git commit history here.
- [x] "Count d’Artigas" in chapter-1.xhtml should be in blockquotes.
- [x] chapter-5.xhtml has the sub-title of "(Notes by Simon Hart, the Engineer.)" I would put that into the <hgroup> with a `<h4>` tag. You can ask about this on the mailing list to make sure.
- [x] In chapter-5.xhtml there should be a `<hr/>` tag right before the paragraph beginning with "How long have I been asleep?"
- [x] In chapter-6.xhtml there should be a `<hr/>` tag right before the paragraph beginning with "The next morning I rise at daybreak"
- [x] In chapter-8.xhtml I don't know how to correctly style "Thomas Hart, Engineer." You might just want to right-align it? Please ask on the mailing list.
- [x] At the end of chapter-17.xhtml I would put "End of Engineer Simon Hart’s Notes." into a blockquote.
- [x] For the diary dates in `<i>` tags, you should check on the mailing list if that's the correct way to style them. I think you did it correctly but am not sure.

Some of these changes might impact `local.css` so make sure to update that as well.

**Comment by bobrk** [comment]
Thanks, I like the subtitle for chapter 5, so that's done. I'll ask about the other ones and take a deep breath and rebase that editorial commit. Thanks.

**Comment by bobrk** [comment]
Ok, I've addressed all these and pushed the changes.
